name: 'oci-cli'
description: 'Installing oci-cli (Oracle Cloud Infrastructure CLI)'
author: 'Christophe Pruvost @cpruvost'
inputs:
  user:
    description: 'OCI User'
    required: true
  fingerprint:
    description: 'OCI Fingerprint'
    required: true
  tenancy:
    description: 'OCI Tenancy'
    required: true
  region:
    description: 'OCI Region'
    required: true
  api_key:
    description: 'OCI API Key'
    required: true
  inlineScript:
    description: 'Specify the script here'
    required: true
outputs:
  time:
    description: "The greeting time"
branding:
  icon: 'cloud'
  color: 'red'    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user }}
    - ${{ inputs.fingerprint }}
    - ${{ inputs.tenancy }}
    - ${{ inputs.region }}
    - ${{ inputs.api_key }}
