name: 'Hello OCI User'
description: 'Greet someone and record the time'
inputs:
  oci-user:  # id of input
    description: 'OCI User'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
