name: ci

on: 
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: Run oci-cli
        uses: cpruvost/autoci-github-cli@main
        with:
          user: "${{ secrets.OCI_USER }}"
          fingerprint: "${{ secrets.OCI_FINGERPRINT }}"
          tenancy: "${{ secrets.OCI_TENANCY }}"
          region: "${{ secrets.OCI_REGION }}"
          api_key: |
            ${{ secrets.OCI_API_KEY }}
          inlineScript: |
            echo "Hello Script"
            /github/home/bin/oci iam region list 

      ##- run: cat ~/.oci/config

      ##- run: oci -v